## Deploy contents of folder to Shiny Server VM

name: Deploy to Shiny

on:
  push:
    paths:
    - 'accident-app/**' 
    branches: [ main ]
  pull_request:
    paths:
        - 'accident-app/**' 
    branches: [ main ]

jobs:

    deploy:
        name: Deploy to Shiny Server
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: copy files via ssh key
              uses: appleboy/scp-action@master
              with: 
                host: ${{ secrets.SHINYHOST }}
                username: ${{ secrets.SHINYUSERNAME }}
                key: ${{ secrets.SHINYKEY }}
                port: ${{ secrets.SHINYPORT }}
                source: "accident-app/app.R"
                target: "~"
