## Deploy contents of folder to Shiny Server VM

name: Deploy to Shiny

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    deploy:
        name: Deploy to Shiny Server
        runs-on: ubuntu-latest
        needs: train

        steps:

        ###  If you need to open the SSH port temporarily on the Shiny Server, uncomment this section

        #   - name: dig +short myip.opendns.com @resolver1.opendns.com
        #     run: dig +short myip.opendns.com @resolver1.opendns.com
    
        #   - name: Add NSG Rule
        #     uses: venura9/manage-nsg@master
        #     id: rule
        #     with:
        #       azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
        #       rule-nsg-resource-group-name: ${{ secrets.SHINY_RG }}
        #       rule-nsg-name: ${{ secrets.SHINY_NSG }}
        #       rule-inbound-port: 22
    
        #   - name: Print Created NSG Rule Name
        #     run: echo "Rule Name ${{ steps.rule.outputs.rule_name }}"
    
          - uses: actions/checkout@master

          - name: copy files via ssh key
            uses: appleboy/scp-action@master
            with: 
              host: ${{ secrets.SHINYHOST }}
              username: ${{ secrets.SHINYUSERNAME }}
              key: ${{ secrets.SHINYKEY }}
              source: "accident-app/app.R"
              target: "~"

        #  Re-close temporarily opened SSH port 
        #   - name: Remove NSG Rule
        #     uses: venura9/manage-nsg@master
        #     with: 
        #       azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
        #       rule-id-for-removal: ${{ steps.rule.outputs.rule_name }}
        #       rule-nsg-resource-group-name: ${{ secrets.SHINY_RG }}
        #       rule-nsg-name: ${{ secrets.SHINY_NSG }}
  